name: Deploy Launcher

on:
  workflow_dispatch: # Activado solo por el workflow maestro

jobs:
  deploy-launcher:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Copiar el archivo launcher a la carpeta de construcción
      - name: Prepare Launcher for Deployment
        run: |
          mkdir -p build
          cp index.html build/

      # Paso 3: Desplegar el launcher en GitHub Pages
      - name: Deploy Launcher to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          keep_files: true
