name: Deploy Static Projects

on:
  workflow_dispatch: # Activado solo por el workflow maestro

jobs:
  deploy-static:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - repasoJS

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Copiar los archivos del proyecto estático al directorio de construcción
      - name: Prepare Static Build Output
        run: |
          mkdir -p build/${{ matrix.project }}
          cp -r ${{ matrix.project }}/. build/${{ matrix.project }}/. # Copia todos los archivos

      # Paso 3: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/${{ matrix.project }}
          keep_files: true
