name: Deploy Vue.js Projects

on:
  push:
    branches:
      - main

jobs:
  deploy-vue:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - guitarrala-vue # Lista de proyectos Vue.js

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Paso 3: Construir proyectos Vue.js
      - name: Install and Build
        working-directory: ${{ matrix.project }}
        run: |
          npm install
          npm run build

      # Paso 4: Mover los archivos generados al directorio build
      - name: Move Vue Build Output
        run: |
          mkdir -p build/${{ matrix.project }}
          mv ${{ matrix.project }}/dist/* build/${{ matrix.project }}

      # Paso 5: Desplegar a gh-pages
      - name: Deploy Vue to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
