name: Deploy Launcher

on:
  workflow_dispatch: # Activado solo por el workflow maestro

jobs:
  deploy-launcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Launcher
        run: |
          mkdir -p build/
          cp index.html build/

      - name: Deploy Launcher to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
