name: Deploy Launcher

on:
  push:
    branches:
      - main

jobs:
  deploy-launcher:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Crear carpeta build y copiar lanzadera
      - name: Copy Launcher
        run: |
          mkdir -p build/
          cp index.html build/

      # Paso 3: Desplegar lanzadera a gh-pages
      - name: Deploy Launcher to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
