name: Deploy Multiple Projects to GitHub Pages

on:
  push:
    branches:
      - main # Ejecutar en cada push a la rama main

jobs:
  deploy-static:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - repasoJS # Lista de proyectos estáticos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Static Projects
        run: |
          mkdir -p build/${{ matrix.project }}
          cp -r ${{ matrix.project }}/* build/${{ matrix.project }}

      - name: List Build Directory
        run: ls -R build/

  deploy-vue:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - guitarrala-vue # Lista de proyectos Vue.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        working-directory: ${{ matrix.project }}
        run: |
          npm install
          npm run build

      - name: Move Vue Build Output
        run: |
          mkdir -p build/${{ matrix.project }}
          mv ${{ matrix.project }}/dist/* build/${{ matrix.project }}

      - name: List Build Directory
        run: ls -R build/

  deploy-to-gh-pages:
    needs: [deploy-static, deploy-vue]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Build Directory
        run: mkdir -p build/

      - name: Copy Launcher
        run: cp index.html build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
