name: Deploy Vue.js Projects

on:
  workflow_dispatch: # Activado solo por el workflow maestro

jobs:
  deploy-vue:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - guitarrala-vue

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        working-directory: ${{ matrix.project }}
        run: |
          npm install
          npm run build

      - name: Move Vue Build Output
        run: |
          mkdir -p build/${{ matrix.project }}
          mv ${{ matrix.project }}/dist/* build/${{ matrix.project }}

      - name: Deploy Vue to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
