name: Master Deploy Workflow

on:
  workflow_dispatch: # Permite ejecutar manualmente este workflow

jobs:
  deploy-all:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Disparar el workflow de proyectos estáticos
      - name: Trigger Deploy Static Projects
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "deploy-static.yml",
              ref: "main",
              inputs: {
                triggered_by: "master-deploy"
              }
            });

      # Paso 3: Disparar el workflow de proyectos Vue.js
      - name: Trigger Deploy Vue.js Projects
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "deploy-vue.yml",
              ref: "main",
              inputs: {
                triggered_by: "master-deploy"
              }
            });

      # Paso 4: Disparar el workflow de la lanzadera principal
      - name: Trigger Deploy Launcher
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "deploy-launcher.yml",
              ref: "main",
              inputs: {
                triggered_by: "master-deploy"
              }
            });
